W4D4/auth_homework/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

W4D4/auth_homework/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  attr_reader :password
  validates :username, presence: true
  validates :password_digest, presence: { message: 'Password can\'t be blank' }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true
  before_validation :ensure_session_token

  def password=(password)
    #no need to assign as a string?
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    #then why new a BCrypt password with a BCrypt object?
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

W4D4/auth_homework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :exception


  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.try(:reset_session_token)
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

end

W4D4/auth_homework/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user.nil?
      render json: 'wrong credentials'
    else
      login!(user)
      redirect_to user_url(user)
    end

  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

W4D4/auth_homework/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]

  def new
    @user = User.new
    if current_user
      redirect_to user_url(current_user)
    else
      render :new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      render json: @user.errors.full_messages
    end
  end

  def show
    render :show
  end


  private

  def user_params
  params.require(:user).permit(:username, :password)
  end

end

W4D4/auth_homework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthHomework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <ul>
        <li>Logged in as: <%= current_user.username  %></li>
        <li>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete" />
            <input type="submit" value="Logout" />
          </form>
        </li>
      </ul>
    <% end %>

    <%= yield %>

  </body>
</html>

W4D4/auth_homework/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url ) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input name="_method" type="hidden" value="<%= method %>">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input id="user_username" name="user[username]" type="text">
  <br>

  <label for="user_password">Password</label>
  <input id="user_password" name="user[password]" type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

W4D4/auth_homework/app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", user: @user %>

W4D4/auth_homework/app/views/users/show.html.erb
<h1><%= current_user.username %></h1>

<br>

<p>Hello, dear user!</p>